name: Sync(同步/升级部署脚本) #一般无需手动执行,部署脚本每次执行就是部署最新代码,这个脚本只是用来升级部署脚本,部署脚本基本不更新
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11,需要repo和workflow权限
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync v2ray
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/free18/v2ray.git"
          source_branch: "main"
          destination_branch: "syc"
          github_token: ${{ secrets.PAT }}
